/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConcertsRouteImport } from './routes/concerts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as LaterRouteImport } from './routes/later'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as ArtistsSlugRouteImport } from './routes/artists/$slug'
import { Route as FamiliesIndexRouteImport } from './routes/families/index'
import { Route as FamiliesSlugRouteImport } from './routes/families/$slug'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistorySlugRouteImport } from './routes/history/$slug'
import { Route as HistoryCultureRouteImport } from './routes/history/culture'
import { Route as HistoryTimelineRouteImport } from './routes/history/timeline'
import { Route as StylesIndexRouteImport } from './routes/styles/index'
import { Route as StylesSlugRouteImport } from './routes/styles/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsRoute = ConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const LaterRoute = LaterRouteImport.update({
  id: '/later',
  path: '/later',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesSlugRoute = FamiliesSlugRouteImport.update({
  id: '/families/$slug',
  path: '/families/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySlugRoute = HistorySlugRouteImport.update({
  id: '/history/$slug',
  path: '/history/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCultureRoute = HistoryCultureRouteImport.update({
  id: '/history/culture',
  path: '/history/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryTimelineRoute = HistoryTimelineRouteImport.update({
  id: '/history/timeline',
  path: '/history/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesIndexRoute = StylesIndexRouteImport.update({
  id: '/styles/',
  path: '/styles/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesSlugRoute = StylesSlugRouteImport.update({
  id: '/styles/$slug',
  path: '/styles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concerts': typeof ConcertsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/foundation': typeof FoundationRoute
  '/later': typeof LaterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/work': typeof WorkRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/history/$slug': typeof HistorySlugRoute
  '/history/culture': typeof HistoryCultureRoute
  '/history/timeline': typeof HistoryTimelineRoute
  '/styles/$slug': typeof StylesSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/styles/': typeof StylesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concerts': typeof ConcertsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/foundation': typeof FoundationRoute
  '/later': typeof LaterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/work': typeof WorkRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/history/$slug': typeof HistorySlugRoute
  '/history/culture': typeof HistoryCultureRoute
  '/history/timeline': typeof HistoryTimelineRoute
  '/styles/$slug': typeof StylesSlugRoute
  '/artists': typeof ArtistsIndexRoute
  '/families': typeof FamiliesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/styles': typeof StylesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concerts': typeof ConcertsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/foundation': typeof FoundationRoute
  '/later': typeof LaterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/work': typeof WorkRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/families/$slug': typeof FamiliesSlugRoute
  '/history/$slug': typeof HistorySlugRoute
  '/history/culture': typeof HistoryCultureRoute
  '/history/timeline': typeof HistoryTimelineRoute
  '/styles/$slug': typeof StylesSlugRoute
  '/artists/': typeof ArtistsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/styles/': typeof StylesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concerts'
    | '/contact'
    | '/donate'
    | '/events'
    | '/foundation'
    | '/later'
    | '/sitemap.xml'
    | '/sources'
    | '/work'
    | '/artists/$slug'
    | '/families/$slug'
    | '/history/$slug'
    | '/history/culture'
    | '/history/timeline'
    | '/styles/$slug'
    | '/artists/'
    | '/families/'
    | '/history/'
    | '/styles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concerts'
    | '/contact'
    | '/donate'
    | '/events'
    | '/foundation'
    | '/later'
    | '/sitemap.xml'
    | '/sources'
    | '/work'
    | '/artists/$slug'
    | '/families/$slug'
    | '/history/$slug'
    | '/history/culture'
    | '/history/timeline'
    | '/styles/$slug'
    | '/artists'
    | '/families'
    | '/history'
    | '/styles'
  id:
    | '__root__'
    | '/'
    | '/concerts'
    | '/contact'
    | '/donate'
    | '/events'
    | '/foundation'
    | '/later'
    | '/sitemap.xml'
    | '/sources'
    | '/work'
    | '/artists/$slug'
    | '/families/$slug'
    | '/history/$slug'
    | '/history/culture'
    | '/history/timeline'
    | '/styles/$slug'
    | '/artists/'
    | '/families/'
    | '/history/'
    | '/styles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcertsRoute: typeof ConcertsRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FoundationRoute: typeof FoundationRoute
  LaterRoute: typeof LaterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  WorkRoute: typeof WorkRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  FamiliesSlugRoute: typeof FamiliesSlugRoute
  HistorySlugRoute: typeof HistorySlugRoute
  HistoryCultureRoute: typeof HistoryCultureRoute
  HistoryTimelineRoute: typeof HistoryTimelineRoute
  StylesSlugRoute: typeof StylesSlugRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  StylesIndexRoute: typeof StylesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts': {
      id: '/concerts'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof ConcertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/later': {
      id: '/later'
      path: '/later'
      fullPath: '/later'
      preLoaderRoute: typeof LaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$slug': {
      id: '/families/$slug'
      path: '/families/$slug'
      fullPath: '/families/$slug'
      preLoaderRoute: typeof FamiliesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$slug': {
      id: '/history/$slug'
      path: '/history/$slug'
      fullPath: '/history/$slug'
      preLoaderRoute: typeof HistorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/culture': {
      id: '/history/culture'
      path: '/history/culture'
      fullPath: '/history/culture'
      preLoaderRoute: typeof HistoryCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/timeline': {
      id: '/history/timeline'
      path: '/history/timeline'
      fullPath: '/history/timeline'
      preLoaderRoute: typeof HistoryTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/': {
      id: '/styles/'
      path: '/styles'
      fullPath: '/styles/'
      preLoaderRoute: typeof StylesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/$slug': {
      id: '/styles/$slug'
      path: '/styles/$slug'
      fullPath: '/styles/$slug'
      preLoaderRoute: typeof StylesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcertsRoute: ConcertsRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FoundationRoute: FoundationRoute,
  LaterRoute: LaterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  WorkRoute: WorkRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  FamiliesSlugRoute: FamiliesSlugRoute,
  HistorySlugRoute: HistorySlugRoute,
  HistoryCultureRoute: HistoryCultureRoute,
  HistoryTimelineRoute: HistoryTimelineRoute,
  StylesSlugRoute: StylesSlugRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  StylesIndexRoute: StylesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
